### PR TITLE
Make `rapidfuzz` optional on `sys_platform=emscripten`

### PR DESCRIPTION
**Pull request by michaelweinold**
...until:

 - https://github.com/brightway-lca/brightway-live/issues/59

is ready, this would fix:

 - https://github.com/brightway-lca/brightway-live/issues/60
 - https://github.com/brightway-lca/brightway-live/issues/57

### CODE REVIEW

**Comment by michaelweinold** [comment]
...hmmm, that is annoying. I just added [the same condition to my testing package](https://github.com/michaelweinold/test_wasm_platform_specific_dependencies/blob/a5cc452c2f4dad084163db8a9bc8fcf8a64c7e1c/pyproject.toml#L16) - and the build ran fine there.

**Comment by michaelweinold** [comment]
...must have been the semicolon.

**Comment by michaelweinold** [comment]
@cmutel, not sure what black magic I need to re-run the checks on this PR. Otherwise ready for review.

**Comment by cmutel** [comment]
I think the review comes before CI, though I don't really understand that... Don't we also need to shortcircuit the calls which use rapidfuzz, or am I missing other commits or PRs? It seems like this would just lead to an import error.

**Comment by michaelweinold** [comment]
Since you answer to my question 

> Is there already a fallback such that whatever-was-used-before-rapidfuzz is used instead, when rapidfuzz is not available?

Was "Yup", I assumed all those short-circuits would be in place. Maybe I should have had a look at [the link you provided](https://github.com/brightway-lca/brightway2-data/commit/61770a99ebe029648b4f31ba8dd3e92b63e92709)...

**Review by cmutel — APPROVED** [review]

**Comment by cmutel** [comment]
OK, CI isn't running because the code didn't change, only the build config.

**Comment by michaelweinold** [comment]
Commit that introduced `rapidfuzz` and `DamerauLevenshtein.distance`:

 - https://github.com/brightway-lca/brightway2-data/commit/9e3e6138783113d12e9791b1be6baa81687d5096

Since the [`string_distance.py` file](https://github.com/brightway-lca/brightway2-data/blob/f426ea5966543cc5bdb543485e7c21b2a59abf4d/bw2data/string_distance.py) is still present, we could simply have `bw2data` fall back to it if `rapidfuzz` is not installed?

**Comment by cmutel** [comment]
> Since the [string_distance.py file](https://github.com/brightway-lca/brightway2-data/blob/f426ea5966543cc5bdb543485e7c21b2a59abf4d/bw2data/string_distance.py) is still present, we could simply have bw2data fall back to it if rapidfuzz is not installed?

Sure, that would work; the API might be slightly different but we can control it in the file we included (i.e. make it fit `rapidfuzz`).

**Comment by michaelweinold** [comment]
...ok, I think it's all ready - you're already falling back to the [string_distance.py file](https://github.com/brightway-lca/brightway2-data/blob/f426ea5966543cc5bdb543485e7c21b2a59abf4d/bw2data/string_distance.py) anyway!

**Pull request merged**
